name: Job Finder Daily

on:
  schedule:
    - cron: "0 8 * * *"   # every day at 8AM UTC
  workflow_dispatch:       # allows manual trigger

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run job finder
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python jobfinder.py
